<?php

return [
    'files' => 'files',
    'method' => 'method',
    'domain' => 'domain',
    'user_id' => 'user_id',
    'type' => 'type',
    'sub_menu' => 'sub_menu',
    'svg' => 'svg',
    'menu' => 'menu',
    'show_value' => 'show_value',
    'my_profile_form' => 'my_profile_form',
    'text' => 'text',
    'move_btn_right' => 'move_btn_right',
    'key' => 'key',
    'educational_jobs' => 'educational_jobs',
    'include_star' => 'include_star',
    'col' => 'col',
    'input' => 'input',
    'prop' => 'prop',
    'value' => 'value',
    'label' => 'label',
    'id' => 'id',
    'user' => 'user',
    'alert' => 'alert',
    'url' => 'url',
    'active_admins' => 'active_admins',
    'active_users' => 'active_users',
    'svg' => 'svg',
    'details' => 'details',
    'priv' => 'priv',
    'data' => 'data',
    'lands' => 'lands',
    'admins' => 'admins',
    'users' => 'users',
    'title' => 'title',
    'order' => 'order',
    'asc' => 'asc',
    'desc' => 'desc',
];
